[kijanikiosk]
api ansible_host=10.185.172.42
payments ansible_host=10.185.172.168
logs ansible_host=10.185.172.234

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/cyrus/.ssh/cyruskey
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
